# Artificial Neural Networks

---

## Import the libraries

In [103]:
import numpy as np
import pandas as pd
import tensorflow as tf


---

## Import the dataset

In [104]:
dataset = pd.read_csv('0800-Data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [105]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [106]:
print(y)

[1 0 1 ... 1 1 0]



---

## Encode categorical data

In [107]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [108]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


---

## Split the dataset

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


---

## Feature Scaling

In [110]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


---

## Build the ANN

### Initialize ANN

In [111]:
ann = tf.compat.v2.keras.Sequential()

### Add the input layer and first hidden layer

In [112]:
ann.add(tf.compat.v2.keras.layers.Dense(units=6, activation='relu'))

### Add the second hidden layer

In [113]:
ann.add(tf.compat.v2.keras.layers.Dense(units=6, activation='relu'))

### Add the output layer

In [114]:
ann.add(tf.compat.v2.keras.layers.Dense(units=1, activation='sigmoid'))


---

## Train the ANN

In [115]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [116]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100


250/250 [==============================] - 1s 819us/step - loss: 0.5479 - accuracy: 0.7757
Epoch 2/100
250/250 [==============================] - 0s 749us/step - loss: 0.4662 - accuracy: 0.7981
Epoch 3/100
250/250 [==============================] - 0s 731us/step - loss: 0.4398 - accuracy: 0.8050
Epoch 4/100
250/250 [==============================] - 0s 755us/step - loss: 0.4257 - accuracy: 0.8144
Epoch 5/100
250/250 [==============================] - 0s 725us/step - loss: 0.4167 - accuracy: 0.8190
Epoch 6/100
250/250 [==============================] - 0s 747us/step - loss: 0.4087 - accuracy: 0.8242
Epoch 7/100
250/250 [==============================] - 0s 728us/step - loss: 0.4007 - accuracy: 0.8314
Epoch 8/100
250/250 [==============================] - 0s 765us/step - loss: 0.3919 - accuracy: 0.8369
Epoch 9/100
250/250 [==============================] - 0s 733us/step - loss: 0.3832 - accuracy: 0.8388
Epoch 10/100
250/250 [==============================] - 0s 747us/step - loss: 0.3750 


---

## Predict the results

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [117]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 48ms/step
[[False]]


### Predicting using the Test set

In [118]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

63/63 [==============================] - 0s 696us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [1 1]]



---

## Make the Confusion Matrix

In [119]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))

[[1540   45]
 [ 211  204]]


In [120]:
print(accuracy_score(y_test, y_pred))

0.872
